import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/queryProvider";

export const metadata: Metadata = {
  title: "Cafe Parvaz",
  description: "Generated by ali & bardia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <QueryProvider>
        <body>{children}</body>
      </QueryProvider>
    </html>
  );
}
